### ISSUE TITLE
UX changing account

### ISSUE THREAD

**Issue by RaphOb** [TikouWeb/gcp-switch-configuration#5]
I don't know if it's normal, but to switch accounts, I have to click inside the circle. Should not be on the card ?

**Comment by TikouWeb** [comment]
@RaphOb Thank you for reporting the issue.

Short answer: Yes, the behavior you observed is normal, but we are considering enhancements to the UI.

Initially, the functionality to click on the card was implemented. However, we later introduced features allowing users to select and copy information directly from the card, such as project id and Account email. Consequently, we removed the click functionality and instead added a radio input at the top right of the card.

Why a radio input? It's because only one card should be selectable at a time, and the radio button aligns with this requirement. It's a standard design element commonly used in user interfaces. For a reference, you can see an example here: [Select User Type - Dribbble](https://dribbble.com/shots/20770655--Dailyui064-Select-User-Type).

**Comment by TikouWeb** [comment]
@RaphOb 
We've successfully enhanced the solution for the reported issue. Please check the updated functionality and let us know if it meets your expectations

<img width="1137" alt="Capture d’écran 2023-12-22 à 11 03 51" src="https://github.com/TikouWeb/gcp-switch-configuration/assets/38016624/dc44199b-f134-4689-a0a6-35fcd300b767">

**Comment by TikouWeb** [comment]
@RaphOb 
We've successfully enhanced the solution for the reported issue. Please check the updated functionality and let us know if it meets your expectations
